require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DefectOccurrencesController do

  # This should return the minimal set of attributes required to create a valid
  # DefectOccurrence. As you add validations to DefectOccurrence, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DefectOccurrencesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all defect_occurrences as @defect_occurrences" do
      defect_occurrence = DefectOccurrence.create! valid_attributes
      get :index, {}, valid_session
      assigns(:defect_occurrences).should eq([defect_occurrence])
    end
  end

  describe "GET show" do
    it "assigns the requested defect_occurrence as @defect_occurrence" do
      defect_occurrence = DefectOccurrence.create! valid_attributes
      get :show, {:id => defect_occurrence.to_param}, valid_session
      assigns(:defect_occurrence).should eq(defect_occurrence)
    end
  end

  describe "GET new" do
    it "assigns a new defect_occurrence as @defect_occurrence" do
      get :new, {}, valid_session
      assigns(:defect_occurrence).should be_a_new(DefectOccurrence)
    end
  end

  describe "GET edit" do
    it "assigns the requested defect_occurrence as @defect_occurrence" do
      defect_occurrence = DefectOccurrence.create! valid_attributes
      get :edit, {:id => defect_occurrence.to_param}, valid_session
      assigns(:defect_occurrence).should eq(defect_occurrence)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DefectOccurrence" do
        expect {
          post :create, {:defect_occurrence => valid_attributes}, valid_session
        }.to change(DefectOccurrence, :count).by(1)
      end

      it "assigns a newly created defect_occurrence as @defect_occurrence" do
        post :create, {:defect_occurrence => valid_attributes}, valid_session
        assigns(:defect_occurrence).should be_a(DefectOccurrence)
        assigns(:defect_occurrence).should be_persisted
      end

      it "redirects to the created defect_occurrence" do
        post :create, {:defect_occurrence => valid_attributes}, valid_session
        response.should redirect_to(DefectOccurrence.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved defect_occurrence as @defect_occurrence" do
        # Trigger the behavior that occurs when invalid params are submitted
        DefectOccurrence.any_instance.stub(:save).and_return(false)
        post :create, {:defect_occurrence => {}}, valid_session
        assigns(:defect_occurrence).should be_a_new(DefectOccurrence)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DefectOccurrence.any_instance.stub(:save).and_return(false)
        post :create, {:defect_occurrence => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested defect_occurrence" do
        defect_occurrence = DefectOccurrence.create! valid_attributes
        # Assuming there are no other defect_occurrences in the database, this
        # specifies that the DefectOccurrence created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DefectOccurrence.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => defect_occurrence.to_param, :defect_occurrence => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested defect_occurrence as @defect_occurrence" do
        defect_occurrence = DefectOccurrence.create! valid_attributes
        put :update, {:id => defect_occurrence.to_param, :defect_occurrence => valid_attributes}, valid_session
        assigns(:defect_occurrence).should eq(defect_occurrence)
      end

      it "redirects to the defect_occurrence" do
        defect_occurrence = DefectOccurrence.create! valid_attributes
        put :update, {:id => defect_occurrence.to_param, :defect_occurrence => valid_attributes}, valid_session
        response.should redirect_to(defect_occurrence)
      end
    end

    describe "with invalid params" do
      it "assigns the defect_occurrence as @defect_occurrence" do
        defect_occurrence = DefectOccurrence.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DefectOccurrence.any_instance.stub(:save).and_return(false)
        put :update, {:id => defect_occurrence.to_param, :defect_occurrence => {}}, valid_session
        assigns(:defect_occurrence).should eq(defect_occurrence)
      end

      it "re-renders the 'edit' template" do
        defect_occurrence = DefectOccurrence.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DefectOccurrence.any_instance.stub(:save).and_return(false)
        put :update, {:id => defect_occurrence.to_param, :defect_occurrence => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested defect_occurrence" do
      defect_occurrence = DefectOccurrence.create! valid_attributes
      expect {
        delete :destroy, {:id => defect_occurrence.to_param}, valid_session
      }.to change(DefectOccurrence, :count).by(-1)
    end

    it "redirects to the defect_occurrences list" do
      defect_occurrence = DefectOccurrence.create! valid_attributes
      delete :destroy, {:id => defect_occurrence.to_param}, valid_session
      response.should redirect_to(defect_occurrences_url)
    end
  end

end
